name: CI
on: push

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16"
      - name: Clean install
        run: npm clean-install
      - name: Run unit tests
        run: npm test

  run-e2e-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.17.0-chrome106
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: ln -s . dist/print-puz-react-vite, npx serve dist -p 5173
          wait-on: "http://localhost:5173/print-puz-react-vite"
          browser: chrome

  deploy:
    needs: [run-unit-tests, run-e2e-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16"
      - name: Clean install
        run: npm clean-install
      - name: Build
        run: npm run build
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.event.head_commit.message }}
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^\d+\.\d+\.\d+$'
      - run: echo ${{ steps.regex-match.outputs.match }}
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ (github.ref == 'refs/heads/main') && (steps.regex-match.outputs.match != '') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
