name: CI/CD
on: push

jobs:
  run-unit-tests:
    name: Run Unit Tests (Vitest)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Clean install
        run: npm clean-install
      - name: Lint
        run: npm run lint
      - name: Run unit tests
        run: npm test

  run-e2e-tests:
    name: Run End-to-End Tests (Cypress)
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:24.14.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v7
        with:
          install-command: npm clean-install
          build: npm run build
          start: npm run preview
          # Preview serves dist on 0.0.0.0:5173 (see vite.config.js).
          wait-on: "http://localhost:5173/print-puz-react-vite/"
          browser: chrome

  deploy:
    name: Deploy to gh-pages
    if: github.ref_type == 'tag'
    needs: [run-unit-tests, run-e2e-tests]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Clean install
        run: npm clean-install
      - name: Build
        run: npm run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
